---
# see https://pre-commit.com

exclude: ^go.(mod|sum)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.13
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.0.0
    hooks:
      - id: cspell

  # see: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
      - id: terraform_fmt
