---
name: Terraform Graph Beautifier

on:
  pull_request:
    branches:
      - feature/add-terraform-graph-beautifier
  push:
    branches:
      - feature/add-terraform-graph-beautifier
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

concurrency: terraform-graph-beautifier

env:
  AWS_ACCOUNT_ID: 107662415716
  ENV_NAME: sandbox
  OIDC_IAM_ROLE: sandbox-private-lab-deploy
  TF_PATH: ./terraform/environments/sandbox/base_apne1

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: AWS Credential
        uses: ./.github/actions/aws-credential
        with:
          oidc-iam-role: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_IAM_ROLE }}

      - name: Get current Terraform version
        id: get-tf-version
        run: |
          echo ::set-output name="TERRAFORM_VERSION::$(cat .terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.get-tf-version.outputs.TERRAFORM_VERSION }}

      - name: Get current Go version
        id: get-go-version
        run: |
          echo ::set-output name="GO_VERSION::$(cat .go-version)"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ steps.get-go-version.outputs.GO_VERSION }}"

      # - name: Debug
      #   run: |
      #     pwd
      #     echo "${HOME}"
      #     echo "${GITHUB_WORKSPACE}"
      #     echo "${GOPATH}"
      #     echo "${GOROOT}"
        # env:
        #   GOPATH: /home/runner/work/woodpecker/go
      # - name: Add to PATH
      #   run: export PATH="$PATH:/usr/local/go/bin/"

      - name: Setup terraform-graph-beautifier
        run: |
          # go mod init github.com/tqer39/private-lab
          # export PATH="${PATH}:/usr/local/go/bin"
          # echo "which go ========================================"
          # which go
          # echo "go env ========================================"
          # go env
          # echo ::set-output name="GOPATH::$(go env GOPATH)"
          # echo "PATH: ${PATH}"
          # echo "GOROOT: ${GOROOT}"
          # echo "GOPATH: ${GOPATH}"
          # go get -u github.com/pcasteran/terraform-graph-beautifier
          # go get -u github.com/goccy/go-graphviz
          # go get github.com/pcasteran/terraform-graph-beautifier
          # go get -d github.com/pcasteran/terraform-graph-beautifier
          # go get -u gonum.org/v1/gonum/...
          go install github.com/pcasteran/terraform-graph-beautifier@v0.2.0
          # echo "which terraform-graph-beautifier ========================================"

          # ls "/opt/hostedtoolcache/go/1.17.11/x64/bin"
          # exec "${SHELL}" -l
          # 下記はエラー
          # which terraform-graph-beautifier
          # ls ~/go/bin

          echo "1 ============================================="
          terraform -chdir="${{ env.TF_PATH }}" init -reconfigure
          # terraform -chdir="${{ env.TF_PATH }}" validate
          # terraform -chdir="${{ env.TF_PATH }}" plan
          # terraform -chdir="${{ env.TF_PATH }}" init -upgrade
          echo "2 ============================================="
          # terraform -chdir="${{ env.TF_PATH }}" graph
          # "$HOME/go/bin/terraform-graph-beautifier" -v

          # terraform -chdir="${{ env.TF_PATH }}" graph | "$HOME/go/bin/terraform-graph-beautifier" \
          #   --exclude="module.root.provider" \
          #   --output-type=cyto-html \
          #   > "${{ env.TF_PATH }}/dependence.html"
          echo "3 ============================================="

          # terraform -chdir="${{ env.TF_PATH }}" graph

          # terraform -chdir="${{ env.TF_PATH }}" graph >> input.txt
          sed "s/\%0A//g" input.txt
          # input="$(terraform -chdir=${{ env.TF_PATH }} graph)"
          # input="${input//'%'/'%25'}"
          # input="${input//$'\n'/'%0A'}"
          # input="${input//$'\r'/'%0D'}"
          # echo "$input" >> input.txt

          echo "4 ============================================="
          # "$HOME/go/bin/terraform-graph-beautifier" --input=input.txt \
          #   --exclude="module.root.provider" \
          #   --output-type=cyto-html \
          #   > "./dependence.html"
          # "$HOME/go/bin/terraform-graph-beautifier" -debug -input input.txt -exclude "module.root.provider" \
          #   > "./dependence.html"
          "$HOME/go/bin/terraform-graph-beautifier" \
            -debug \
            -input input.txt \
            -exclude "module.root.provider" \
            -output "${{ env.TF_PATH }}/dependence.html"

          echo "5 ============================================="

      - name: Create branch
        run: |
          DATE="$(date '+%Y-%m-%d')"
          git config user.email "tqer39+github-actions@gmail.com"
          git config user.name "Github Actions"
          git remote set-url origin "https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git switch -c "terraform-graph-beautifier/${DATE}-${GITHUB_RUN_NUMBER}"
          # git add "${{ env.TF_PATH }}/dependence.html"
          # git commit -m "GitHub Actions から差分を Push"
          # git push origin "HEAD:${GITHUB_REF}"
          # git switch main
          # git merge "HEAD:${GITHUB_REF}"
        env:
          TZ: "Asia/Tokyo"

      # - name: Create graph
      #   run: |
